account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.Login.as_view(),name='login'),
    path("logout", views.Logout.as_view(), name="logout"),
    path('register', views.AccountRegistration.as_view(), name='register'),
    
]

team/urls.py
from django.urls import path, include
from . import views

app_name = "nattou"
urlpatterns = [
    path('', views.login, name="top"),
    path('home/', views.HomeView.as_view(), name="home"),
    path('search', views.SearchMovie.as_view(), name="search"),
    path('good/<int:index>', views.send_movie_message, name="good"),
    path('info/<int:index>', views.HomeView.as_view(), name="info"),
]

team_app_sample/urls.py
from django.contrib import admin
from django.urls import path, include
from team import views as team_views
from account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', team_views.index, name='index'),
    # path('announce', team_views.announce, name='announce'),
    # path('clear', team_views.clear, name='clear'),
    # path('api/echo', team_views.echo, name='api_echo'),
    # path('api/hell', team_views.hello, name='api_hello'),
    # path('api/reply', team_views.reply, name='api_reply'),
    path('api/eat',team_views.eat,name='api_eat'),
    path('api/find', team_views.find, name='api_find'),
    path('api/category', team_views.category, name='api_category'),
    path('nattou/', include('team.urls')),
    path('nattou/account/', include('account.urls')),
]

team/models.py
from django.db import models

team/views.py
from django.shortcuts import render, redirect
from django.http import Http404, JsonResponse
from django.core.exceptions import SuspiciousOperation
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from urllib.parse import urlencode
import urllib
import json
from .movie import TMDB, Title
from .slack_auth import Auth
from django.contrib.auth.models import User
from account.models import Account

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from .youtube import Youtube

import requests
import os
import random

WEBHOOK_URL = 'https://hooks.slack.com/services/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'
VERIFICATION_TOKEN = 'rHJmMZnxK2PpCEcBPjeGV3T0'
ACTION_HOW_ARE_YOU = 'HOW_ARE_YOU'
SLACK_BOT_TOKEN = "xoxb-1950703337543-1955290934615-JBA4qXoRISYFGiK7NBomYDSS"
CHANNEL_ID = "C01UB7CA7FG"
YOUTUBE_API = "AIzaSyB2ZmP4ihw1Yb63ZnRHWBtFNM6n7llwFgY"


API = TMDB('eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5ZDQ3YjJjNDlkZmUzYTFlN2MyMWEzYTM5YzNjYTgzNCIsInN1YiI6IjYwNzlkMmE2Nzc3NmYwMDA1ODE4M2NhMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.sk4Rd7NbCbRPaJXcsRqS05YmTpztmM5OgQ6dR5g7Dno')

test_template_1 = "test_page_1.html"

popular_movies = []



# def index(request):
#     positive_replies = Reply.objects.filter(response=Reply.POSITIVE)
#     neutral_replies = Reply.objects.filter(response=Reply.NEUTRAL)
#     negative_replies = Reply.objects.filter(response=Reply.NEGATIVE)

#     context = {
#         'positive_replies': positive_replies,
#         'neutral_replies': neutral_replies,
#         'negative_replies': negative_replies,

#     }
#     return render(request, 'index.html', context)

# def clear(request):
#     Reply.objects.all().delete()
#     return redirect(index)

# def announce(request):
#     if request.method == 'POST':
#         data = {
#             'text': request.POST['message']
#         }
#         post_message(WEBHOOK_URL, data)

#     return redirect(index)

# @csrf_exempt
# def echo(request):
#     if request.method != 'POST':
#         return JsonResponse({})
    
#     if request.POST.get('token') != VERIFICATION_TOKEN:
#         raise SuspiciousOperation('Invalid request.')
    
#     user_name = request.POST['user_name']
#     user_id = request.POST['user_id']
#     content = request.POST['text']

#     result = {
#         'text': '<@{}> {}'.format(user_id, content.upper()),
#         'response_type': 'in_channel'
#     }

#     return JsonResponse(result)

# @csrf_exempt
# def hello(request):
#     if request.method != 'POST':
#         return JsonResponse({})
    
#     if request.POST.get('token') != VERIFICATION_TOKEN:
#         raise SuspiciousOperation('Invalid request.')
    
#     user_name = request.POST['user_name']
#     user_id = request.POST['user_id']
#     content = request.POST['text']

#     result = {
#         'blocks': [
#             {
#                 'type' : 'section',
#                 'text' : {
#                     'type': 'mrkdwn',
#                     'text': '<@{}> How are you?'.format(user_id)
#                 },
#                 'accessory': {
#                     'type': 'static_select',
#                     'placeholder': {
#                         'type': 'plain_text',
#                         'text': 'I am:',
#                         'emoji': True
#                     },
#                     'options': [
#                         {
#                             'text': {
#                                 'type': 'plain_text',
#                                 'text': 'Fine.',
#                                 'emoji': True
#                             },
#                             'value': 'positive'
#                         },
#                         {
#                             'text': {
#                                 'type': 'plain_text',
#                                 'text': 'So so.',
#                                 'emoji': True
#                             },
#                             'value': 'neutral'
#                         },
#                         {
#                             'text': {
#                                 'type': 'plain_text',
#                                 'text': 'Terrible.',
#                                 'emoji': True
#                             },
#                             'value': 'negative'
#                         }
#                     ],
#                     'action_id': ACTION_HOW_ARE_YOU
#                 }
#             }
#         ],
#         'response_type': 'in_channel'
#     }

#     return JsonResponse(result)

# @csrf_exempt
# def reply(request):
#     if request.method != 'POST':
#         return JsonResponse({})
    
#     payload = json.loads(request.POST.get('payload'))
#     print(payload)
#     if payload.get('token') != VERIFICATION_TOKEN:
#         raise SuspiciousOperation('Invalid request.')
    
#     if payload['actions'][0]['action_id'] != ACTION_HOW_ARE_YOU:
#         raise SuspiciousOperation('Invalid request.')
    
#     user = payload['user']
#     selected_value = payload['actions'][0]['selected_option']['value']
#     response_url = payload['response_url']

#     if selected_value == 'positive':
#         reply = Reply(user_name=user['name'], user_id=user['id'], response=Reply.POSITIVE)
#         reply.save()
#         response = {
#             'text': '<@{}> Great! :smile:'.format(user['id'])
#         }
#     elif selected_value == 'neutral':
#         reply = Reply(user_name=user['name'], user_id=user['id'], response=Reply.NEUTRAL)
#         reply.save()
#         response = {
#             'text': '<@{}> Ok, thank you! :sweat_smile:'.format(user['id'])
#         }
#     else:
#         reply = Reply(user_name=user['name'], user_id=user['id'], response=Reply.NEGATIVE)
#         reply.save()
#         response = {
#             'text': '<@{}> Good luck! :innocent:'.format(user['id'])
#         }
    
#     post_message(response_url, response)

#     return JsonResponse({})

# このメソッドは使える
def post_message(url, data):
    headers = {
        'Content-Type': 'application/json',
    }
    req = urllib.request.Request(url, json.dumps(data).encode(), headers)
    with urllib.request.urlopen(req) as res:
        body = res.read()

@csrf_exempt
def eat(request):
    if request.method != 'POST':
        return JsonResponse({})
    
    if request.POST.get('token') != VERIFICATION_TOKEN:
        raise SuspiciousOperation('Invalid request.')

    user_name = request.POST['user_name']
    user_id = request.POST['user_id']
    content = request.POST['text']

    meal = ['ラーメン','カレー','オムライス']
    n  = random.randint(0,len(meal)-1)
    result = {
        'text' : '<@{}> {}'.format(user_id, meal[n]),
        'response_type': 'in_channel' 
    }
    return JsonResponse(result)

@csrf_exempt
def find(request):
    if request.method != 'POST':
        return JsonResponse({})

    if request.POST.get('token') != VERIFICATION_TOKEN:
        raise SuspiciousOperation('Invalid request.')

    user_name = request.POST['user_name']
    user_id = request.POST['user_id']

    title = Title()
    top5_movies = title.get_top5_movies()
    top5_movies_title = [title[0] for title in top5_movies][::-1][:5]
    top5_movies_urls = [ele[1][1] for ele in top5_movies][::-1][:5]
    top5_movies_rates = [ele[1][0] for ele in top5_movies][::-1][:5]
    top5_movies_overview = [ele[1][2] for ele in top5_movies][::-1][:5]

    payload = {
         'blocks': [
            {
                'type': 'section',
                'text': {
                    'type': 'mrkdwn',
                    'text': '人気の映画上位5件を検索しました。'
                }
            },
            {
                'type': 'divider'
            },
            {
                'type': 'section',
                'text': {
                    'type': 'mrkdwn',
                    'text': '*{}*\n{}'.format(top5_movies_title[0], top5_movies_overview[0])
                },
                'accessory': {
                    'type': 'image',
                    'image_url': "{}".format(top5_movies_urls[0]),
                    'alt_text': 'Movie Poster Image'
                }
            },
            {
                'type': 'section',
                'fields': [
                    {
                        'type': 'mrkdwn',
                        'text': '*Average Rating*\n{}'.format(top5_movies_rates[0])
                    }
                ]
            },
            {
                'type': 'divider'
            },
            {
                'type': 'section',
                'text': {
                    'type': 'mrkdwn',
                    'text': '*{}*\n{}'.format(top5_movies_title[1], top5_movies_overview[1])
                },
                'accessory': {
                    'type': 'image',
                    'image_url': '{}'.format(top5_movies_urls[1]),
                    'alt_text': 'Movie Poster Image'
                }
            },
            {
                'type': 'section',
                'fields': [
                    {
                        'type': 'mrkdwn',
                        'text': '*Average Rating*\n{}'.format(top5_movies_rates[1])
                    }
                ]
            },
            {
                'type': 'divider'
            },
            {
                'type': 'section',
                'text': {
                    'type': 'mrkdwn',
                    'text': '*{}*\n{}'.format(top5_movies_title[2], top5_movies_overview[2])
                },
                'accessory': {
                    'type': 'image',
                    'image_url': '{}'.format(top5_movies_urls[2]),
                    'alt_text': 'Movie Poster Image'
                }
            },
            {
                'type': 'section',

team/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>nattou movie viewer</title>
        <link rel="stylesheet" href="{% static '/css/base.css' %}">
        <!--css, javascript は　デザイン担当の人のやってもらう-->
    </head>

    <body>
        <header class="site-header">
            <h1>
             <a class = "natto">natto</a>
            </h1>
                    <form action="/nattou/search" method="post">
                         {% csrf_token %}
                         <input type="search" name="search" id="txt" placeholder="映画を探す" class="search_bar">
                         <input type="image" name="submit" class="search_button" src="{% static '/image/検索アイコン.png' %}">
                    </form>
                 <a href="{% url 'nattou:home' %}"><img class = "home" src="{% static '/image/家の無料アイコン.png' %}" alt = "homeへ戻る"></a>
        </header>

        <div class="movie">
                    {% block movieblock %}
                        <div class="container">
                            {% for index, ele in titles.items %}
                            <div class="box">
                                <form action="{% url 'nattou:info' index %}" method="POST">
                                {% csrf_token %}
                                {% if ele.img_url %}
                                    <input type="image" src="{{ base_img_url_ }}{{ ele.img_url }}" name="image_button">
                                {% elif ele.img_url == None %}
                                    <input type="image" src="{% static '/image/default_movie.jpg' %}" name="image_button" style="width: 500px; height: 281px;">
                                {% endif %}
                                </form>
                                <h2>{{ ele.title }}</h2>
                                <h4>
                                    評価値： <big><span class="star5_rating" data-rate="{{ele.rate}}"></span></big>  {{ ele.rate }} <br>
                                    公開日： {{ ele.release_date }} <br>
                                    <a href="{{  ele.youtube_url }}"><img class = "youtube" src="{% static '/image/youtube.png' %}">この映画の紹介映像をみる</a>
                                </h4>
                                <form action="{% url 'nattou:good' index %}" method="POST">
                                {% csrf_token %}
                                <input type="image" src="{% static '/image/Like.png' %}" name="Like" class="img" style="width: 150px; height: 55px;">
                                </form>
                            </div>
                            {% endfor %}
                        </div>
                    {% endblock %}
         </div>

            {% block genre %}
                <h1>近日公開の映画</h1>
                <article>
                    <div class="container">
                        {% for index, ele in movies.items %}
                        <div class="box">
                            <form action="{% url 'nattou:info' index %}" method="POST">
                            {% if ele.img_url %}
                                <input type="image" src="{{ base_img_url_ }}{{ ele.img_url }}" name="image">
                            {% else %}
                                <input type="image" src="{% static '/image/default_movie.jpg' %}" name="image" style="width: 500px; height: 281px;">
                            {% endif %}
                            </form>
                            <h2>{{ ele.title }}</h2>
                            <h4>
                                評価値： <big><span class="star5_rating" data-rate="{{ele.rate}}"></span></big>  {{ ele.rate }} <br>
                                公開日： {{ ele.release_date }}
                            </h4>
                            <a href="{{  ele.youtube_url }}"><img class = "youtube" src="{% static '/image/youtube.png' %}">この映画の紹介映像をみる</a>
                            <form action="{% url 'nattou:good' index %}" method="POST">
                            {% csrf_token %}
                            <input type="image" src="{% static '/image/Like.png' %}" name="like" class="img" style="width: 150px; height: 55px;">
                            </form>
                        </div>
                        {% endfor %}
                    </div>
                </article>
            {% endblock %}

    

        <!-- The core Firebase JS SDK is always required and must be listed first -->
        <script src="https://www.gstatic.com/firebasejs/8.4.3/firebase-app.js"></script>
        <!-- TODO: Add SDKs for Firebase products that you want to use
            https://firebase.google.com/docs/web/setup#available-libraries -->
        <script src="https://www.gstatic.com/firebasejs/8.4.3/firebase-analytics.js"></script>
        
        <script>
        // Your web app's Firebase configuration
        // For Firebase JS SDK v7.20.0 and later, measurementId is optional
        var firebaseConfig = {
            apiKey: "AIzaSyAyiWr8yuKzVq8SvARNkPKpyadZ-tENJ38",
            authDomain: "forward-entity-312403.firebaseapp.com",
            projectId: "forward-entity-312403",
            storageBucket: "forward-entity-312403.appspot.com",
            messagingSenderId: "302208104245",
            appId: "1:302208104245:web:17b2ff2765bba752613e7c",
            measurementId: "G-BD058GNSNK"
        };
        // Initialize Firebase
        firebase.initializeApp(firebaseConfig);
        firebase.analytics();
        </script>
    </body>

</html>

<!--基本はこのtemplateを継承元にするべき?-->

team/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <title>Slack Sample Application</title>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">
        Slack Sample Application
      </a>
    </nav>

    <div id="sample-page">
      <a href="{% url 'nattou:login' %}">
        <h1>Test Page</h1>
      </a>
    </div>

    <div class="container">
      <div class="jumbotron">
        <h1>How are you?</h1>
        <form action="{% url 'announce' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="message">Send a test message to Slack.</label>
            <textarea id="message" name="message" class="form-control" rows="3"></textarea>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Send</button>
          </div>
        </form>
      </div>
      <a class="btn btn-danger" href="{% url 'clear' %}">Reset</a>

      <div class="card mt-3">
        <h3 class="card-header">
          Fine people
        </h3>
        <div class="card-body">
          {% for reply in positive_replies %}
          <p> {{reply.user_name}} </p>
          {% endfor %}
        </div>
      </div>
      <div class="card mt-3">
        <h3 class="card-header">
          So so people
        </h3>
        <div class="card-body">
          {% for reply in neutral_replies %}
          <p> {{reply.user_name}} </p>
          {% endfor %}
        </div>
      </div>
      <div class="card mt-3">
        <h3 class="card-header">
          Terrible people
        </h3>
        <div class="card-body">
          {% for reply in negative_replies %}
          <p> {{reply.user_name}} </p>
          {% endfor %}
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
      integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>
  </body>

</html>

team/templates/loginpage.html
<!-- 最初のページ -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login Page</title>
    </head>
    <body>
        <nav>
            <h1>ここからSlackアカウントを使ってログインしてください</h1>
        </nav>
        <div>
            <a href="https://slack.com/oauth/v2/authorize?user_scope=identity.basic&client_id=1950703337543.1976204162676">
                <img src="https://platform.slack-edge.com/img/sign_in_with_slack.png">
            </a>
        </div>
    </body>
</html>

team/templates/movie_info.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Movie Info</title>
    </head>
    <body>
        <img src="{{ thumbnail_url.url }}">
    </body>
</html>

team/templates/regist.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Regist Page</title>
    </head>
    <body>
        <head></head>
        <h1>まだアカウントが作成されていないようです。</h1>
        <br>
        <h1>ユーザー名、及び、アイコン画像を設定してください</h1>
        <br>
        <form action="{% url 'nattou:home' %}" method="POST">
            {% csrf_token %}
        <ul class="profile_list">
            <li>ユーザー名</li>
            <li><input type="text" class="user_name"　value="好きな名前を入力してくだい" name="user_name"></li>

        </ul>
        <p><input type="submit" value="決定"></p>
        </form>
    </body>
</html>

team/templates/search.html
{% extends "home.html" %}
{% load static %}
<!DOCTYPE html>

{% block movieblock %}
<article>
    <div class="container">
        {% for index, ele in movies.items %}
        <div class="box">
            <form action="{% url 'nattou:info' index">
                {% csrf_token %}
                {% if ele.img_url %}
                <input  type="image" src="{{ base_img_url_ }}{{ ele.img_url }}" name="image_button">
                {% elif ele.img_url == None %}
                <input type="image" src="{% static '/image/default_movie.jpg' %}" name="image_button" style="width: 500px; height: 281px;">
                {% endif %}
            </form>
            <h2>{{ ele.title }}</h2>
            <h4>
                評価値: <big><span class="star5_rating" data-rate="{{ele.rate}}"></span></big> {{ ele.rate }} <br>
                公開日: {{ ele.release_date }}
            </h4>
            <a href="{{ ele.youtube_url }}">この映画の紹介映像をみる</a>
            <form action="{% url 'nattou:good' index %}" method="POST">
                {% csrf_token %}
                <input type="image" src="{% static '/image/Like.png' %}" name="Like" class="img" style="width: 150px; height: 55px;">
            </form>
        </div>
    {% endfor %}
    </div>
</article>
{% endblock %}

{% block genre %}
<h1>類似の作品</h1>
<article>
    <div class="container">
        {% for index, ele in similar.items %}
        <div class="box">
            <form action="{% url 'nattou:info' index %}" method="POST">
                {% csrf_token %}
                {% if ele.img_url %}
                <input type="image" src="{{ base_img_url_ }}{{ ele.img_url }}" name="image">
                {% else %}
                <input type="image" src="{% static '/image/default_movie.jpg' %}" name="image" style="width: 500px; height: 281px;">
                {% endif %}
            </form>
        <h2>{{ ele.title }}</h2>
        <h4>
            評価値: <big><span class="star5_rating" data-rate="{{ele.rate}}"></span></big> {{ ele.rate }} <br>
            公開日: {{ ele.release_date }}
        </h4>
        <a href="{{ ele.youtube_url }}">この映画の紹介映像をみる</a>
        <form action="{% url 'nattou:good' index %}" method="POST">
            {% csrf_token %}
            <input type="image" src="{% static '/image/Like.png' %}" name="Like" class="img" style="width: 150px; height: 55px;">
        </form>
       </div>
       {% endfor %}
    </div>
</article>
{% endblock %}

team/templates/userlist.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>User List</title>
    </head>

    <header></header>

    <body>
        
    </body>
</html>